config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'user_rooms/show'
  get 'rooms/show'
  get 'rooms/create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  # ログインと新規登録の時の指定

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => "homes#about"
  post 'create/:id' => 'relationships#create', as:'follow'
  post 'destroy/:id' => 'relationships#destroy', as:'unfollow'
  get '/search' => 'search#search'
  resources :users, only: [:index, :show, :edit, :update]  do
    member do
      get :following, :followers
    end
  end
  
  # ————DM機能—————————————————————————————————
  resources :rooms, only: [:show, :create]
  resources :user_rooms, only: [:show, :create]
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  # ———————————————————————————————————————————
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/views/shares/_booklist.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to (attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"), user_path(book.user.id) %>
      </td>
      <td>
        <%= link_to book.title, book_path(book.id) %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <td id = 'favorite_form_<%= book.id %>'>
        <%= render 'favorites/favorite_form', book: book %>
      </td>
      <td>
        コメント数:<%= book.book_comments.count %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/shares/_error_message.html.erb
<div class="text-danger">
  <% if error.errors.any? %>
    <%= pluralize(error.errors.count, "error") %> prohibited this obj from being saved:
    <li>
      <% error.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </li>
  <% end %>
</div>

app/views/shares/_follow_button.html.erb
<% unless user == current_user %>
  <% if current_user.following?(user) %>
    <%= link_to 'unfollow', unfollow_path(user.id), method: :POST, class:"btn btn-secondary" %>
  <% else %>
    <%= link_to 'follow', follow_path(user.id), method: :POST, class:"btn btn-primary" %>
  <% end %>
<% end %>

app/views/shares/_listnewbook.html.erb
<%= form_with model:book, url: books_path, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">
      Title
    </label>
    <p><%= f.text_field :title %></p>
  </div>
  <div class="form-group">
    <label for="book_opinion">
      Opinion
    </label>
    <p><%= f.text_field :body %></p>
  </div>
  <div class="form-group">
    <p><%= f.submit 'Create Book', class:"btn btn-success" %></p>
  </div>
<% end %>

app/views/shares/_search_form.html.erb
<!-- 検索フォーム -->
<%= form_with url: search_path, method: :get, local: :true do |f| %>
  <%= f.select :range, options_for_select([['User'], ['Book']]) %>
  <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致", "partial_match"], ["前方一致", "forward_match"], ["後方一致", "backward_match"]]) %>
  <%= f.text_field :word %>
  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>

app/views/shares/_user_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td>
        <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
      </td>
      <td>
        <%= user.name %>
      </td>
      <td>
        <p>フォロー数:</p><%= user.follower.count %>
      </td>
      <td>
        <p>フォロワー数:</p><%= user.followed.count %>
      </td>
      <td>
        <%= render 'shares/follow_button', user: user %>
      </td>
      <td>
        <%= link_to "Show", user_path(user.id) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/shares/_userinfo.html.erb
<table class="table">
  <tbody>
    <tr>
      <th><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></th>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>
        follows
      </th>
      <th>
        <%= link_to user.follower.count, following_user_path(user) %>
      </th>
    </tr>
    <tr>
      <th>
        followers
      </th>
      <th>
        <%= link_to user.followed.count, followers_user_path(user) %>
      </th>
    </tr>
    <tr>
      <th>
        <%= render 'shares/follow_button', user: user %>
      </th>
    </tr>
    <tr>
      <th>
        <% if current_user != user %>
          <%= link_to 'チャットする', chat_path(user) %>
        <% end %>
      </th>
    </tr>
  </tbody>
</table>

<%= link_to '', edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>