config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'user_rooms/show'
  get 'rooms/show'
  get 'rooms/create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  # ログインと新規登録の時の指定

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => "homes#about"
  post 'create/:id' => 'relationships#create', as:'follow'
  post 'destroy/:id' => 'relationships#destroy', as:'unfollow'
  get '/search' => 'search#search'
  resources :users, only: [:index, :show, :edit, :update]  do
    member do
      get :following, :followers
    end
  end
  
  # ————DM機能—————————————————————————————————
  resources :rooms, only: [:show, :create]
  resources :user_rooms, only: [:show, :create]
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  # ———————————————————————————————————————————
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :book
  belongs_to :user
  
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    @book_comments = book.book_comments
    if comment.save
      render :create
      flash[:notice] = "You have created comment successfully."
    else
      render 'books/show'
    end
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book_comments = BookComment.all
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comment_form.html.erb
<%= form_with(model:[book, book_comment]) do |f| %>
  <%= f.text_area :comment, size:"90x5" %>
  <%= f.submit '送信'%>
<% end %>

app/views/book_comments/_book_comment_list.html.erb
<table class="table book_comments">
  <tbody>
  <% @book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to (attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"), user_path(book_comment.user.id) %>
        <%= book_comment.user.name %>
      </td>
      <td>
        <%= book_comment.comment %>
      </td>
      <td>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/book_comments/create.js.erb
$("#comments_area").html("<%= j(render 'book_comment_list', { book: @book }) %>");
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'book_comment_list', { book: @book }) %>");