config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'user_rooms/show'
  get 'rooms/show'
  get 'rooms/create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  # ログインと新規登録の時の指定

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => "homes#about"
  post 'create/:id' => 'relationships#create', as:'follow'
  post 'destroy/:id' => 'relationships#destroy', as:'unfollow'
  get '/search' => 'search#search'
  resources :users, only: [:index, :show, :edit, :update]  do
    member do
      get :following, :followers
    end
  end
  
  # ————DM機能—————————————————————————————————
  resources :rooms, only: [:show, :create]
  resources :user_rooms, only: [:show, :create]
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  # ———————————————————————————————————————————
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.looks(searches, words)
    if searches == "perfect_match" #完全一致
      @book = Book.where("title LIKE ?", "#{words}")
    else
      @book = Book.where("title LIKE ?", "%#{words}%")
    end
    
    if searches == "partial_match" #部分一致
      @book = Book.where("title LIKE ?", "%#{words}%")
    end
    
    if searches == "forward_match" #前方一致
      @book = Book.where("title LIKE?", "#{words}%")
    else
      @book = Book.where("title LIKE ?", "%#{words}%")
    end

    if searches == "backward_match" #後方一致
      @book = Book.where("title LIKE ?", "%#{words}")
    else
      @book = Book.where("title LIKE ?", "%#{words}%")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
    @user = current_user
    @new_book = Book.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
    flash[:notice] = "Book was successfully destroyed."
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_show.html.erb
<table class="table">
  <tbody>
    <tr>
      <td>
        <p>
          <%= link_to (attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"), user_path(book.user.id) %>
        </p>
        <p><%= link_to book.user.name, user_path(book.user.id) %></p>
      </td>
      <td>
        <%= link_to book.title, book_path(book.id) %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <% if book.user.id == current_user.id %>
      <td>
        <%= link_to 'Edit', edit_book_path(book), class: "btn btn-sm btn-success" %>
      </td>
      <td>
        <%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
      </td>
      <% end %>
      <td id = 'favorite_form_<%= book.id %>'>
        <%= render 'favorites/favorite_form', book: book %>
      </td>
      <td>
        コメント数:<%= book.book_comments.count %>
      </td>
    </tr>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">

    <div class="text-danger">
      <% if @book.errors.any? %>
        <%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:
        <li>
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        </li>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h2>Editing Book</h2>
      <%= form_with model:@book, local: true do |f| %>
      <div class="form-group">
        <label for="book_title">
          Title
        </label>
        <p>
          <%= f.text_field :title %>
        </p>
      </div>
      <div class="form-group">
        <label for="book_opinion">
          Opinion
        </label>
        <p>
          <%= f.text_field :body %>
        </p>
      </div>
      <div class="form-group">
        <p><%= f.submit 'Update Book' %></p>
      </div>
      <% end %>
      
      <p>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
      </p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'shares/error_message', error: @book %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'shares/userinfo', user: @user %>
      
      <h2>New book</h2>
      <%= render 'shares/listnewbook', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%= render 'shares/search_form' %>
      <h2>Books</h2>
      <%= render 'shares/booklist', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'shares/error_message', error: @book_comment %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'shares/userinfo', user: @book.user %>
      <h2>New book</h2>
      <%= render 'shares/listnewbook', book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <%= render 'show', book: @book %>
      <div id="comments_area">
        <%= render 'book_comments/book_comment_list', book: @book, book_comments: @book_comments %>
      </div>
      <%= render 'book_comments/book_comment_form', book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>