config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'user_rooms/show'
  get 'rooms/show'
  get 'rooms/create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  # ログインと新規登録の時の指定

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => "homes#about"
  post 'create/:id' => 'relationships#create', as:'follow'
  post 'destroy/:id' => 'relationships#destroy', as:'unfollow'
  get '/search' => 'search#search'
  resources :users, only: [:index, :show, :edit, :update]  do
    member do
      get :following, :followers
    end
  end
  
  # ————DM機能—————————————————————————————————
  resources :rooms, only: [:show, :create]
  resources :user_rooms, only: [:show, :create]
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  # ———————————————————————————————————————————
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-bland text-light" href="/">
            <span>Bookers</span>
          </a>
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
            </li>
            <li>
              <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
            </li>
            <li>
              <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
            </li>
            <li>
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
            </li>
            <% else %>
            <li>
              <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
            </li>
            <li>
              <%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %>
            </li>
            <li>
              <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light", data: {"turbolinks"=>false} %>
            </li>
            <li>
              <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="container">      
        <div class="row">
          <div class="text-success">
            <% flash.each do |message_type, message| %>
              <%= content_tag(:div, message, class: message_type) %>
            <% end %>
          </div>
        </div>
      </div>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>